config/routes.rb
Logbook::Application.routes.draw do 
  resources :contact_forms, only: [:new, :create]
  resources :users do
     resource :profile, :controller => 'profile'
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :bodylogs
  resources :workouts
  resources :settings, :controller => 'settings', only: [:show, :update]
 
 
  root 'static_pages#home'
  match '/results', to: 'results_pages#index', via: 'post'
  match '/results', to: 'results_pages#index', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout',  to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'contact_forms#new', via: 'get'
  

end

app/controllers/results_pages_controller.rb
class ResultsPagesController < ApplicationController
	include ResultsPagesHelper
	before_action :signed_in_user #check if user = signed in.
	respond_to :html, :json # necessary for in_place_editing.


	##########
	# Index page controller for combined Bodylog and Workoutlog records.
	##########
	def index
		#variables to isplay bodylogs records
		@user = current_user
		@bodylogsTable = @user.bodylogs.paginate page: params[:page], order: 'created_at DESC', per_page: 7 #display 7 results per page in descending order.
		@bodylogs = @user.bodylogs.find(:all, order: :created_at) # find all bodylogs in the order-of created at (so chart will display well upon editing.)
		@date = params[:month] ? Date.parse(params[:month]) : Date.today  # for the calendar date selector
		@profile = @user.profile

		gon.weight = @bodylogs.map{ |row| [row.created_at.beginning_of_day.to_i * 1000, row.weight]} #collect db data to pass to Javascript chart
		gon.kcal = @bodylogs.map{ |row| [row.created_at.beginning_of_day.to_i * 1000, row.kcal]} #collect db data to pass to Javascript chart
		
		#variables/arrays to display workout records. 
		@exercises = get_exercise_list(@user.exercises.all) #see results_pages_helper for 'get_exercise_list' method
		@workouts = @user.workouts.all
		@workoutsTable = @user.workouts.paginate page: params[:page], order: 'created_at DESC', per_page: 7
		@strengthList = get_strength(params[:exercise])	#see results_pages_helper for 'get_strength' method
		gon.strength =  @strengthList.map{ |row| [row.created_at.beginning_of_day.to_i * 1000, row.strength]}  #collect db data to pass to Javascript chart

		if params[:exercise] != nil #To provide graph with the proper name
			gon.exercise_name = params[:exercise] 
		else
			gon.exercise_name = '-' #if no workout selected
		end 
	end
end

app/helpers/results_pages_helper.rb
module ResultsPagesHelper

	#######
	# return strength of all exercises of a given name.
	#######
	def get_strength(exercise)
		strengthlist = Array.new
		exercises = current_user.exercises.where('name =  :name', {:name => exercise})
		exercises.each do |ex|
			if ex.strength != nil
				strengthlist.append(ex) 
			end
		end
		return strengthlist
	end

	#######
	# Method to return right date format for bodylog table.
	#######
	def format_date(my_date)
  		my_date.strftime('%m/%d/%Y')
	end

	######
	# check if target calories within range (allow leeway) and return boolean.
 	######
	def target_kcal(calories, targetkcal)
		if targetkcal == nil || calories == nil
			return nil
		elsif calories > (targetkcal+100) || calories < (targetkcal-100) #100 kcal leeway
			return false
		else
			return true
		end
	end

	#####
	# Remove duplicate exercise names from list (at strength chart)
	####
	def get_exercise_list(exercises)
		exerciseList = Array.new
		exercises.each do |e|
			unless exerciseList.include?(e.name) 
				exerciseList.append(e.name)
			end
		end
		return exerciseList
	end

	########
	# Check if the target weight is reached and allow for a little leeway (0.1 kg)
	######
	def target_weight_reached(weight)
		weighttarget = current_user.profile.weighttarget 
		if weighttarget != nil
			if weight < (weighttarget - 0.10) || weight > (weighttarget + 0.10) # 0.10kg leeway.
				return false
			else
				return true
			end
		else
			return false
		end
	end

	#######
	# return a string for integer rating in database.
	#######
	def display_workout_rating(rating)
		array = ["Excellent", "Good", "Okay", "Not so good", "Bad"]
		if rating == nil
			return nil
		else 
			return array[rating-1] 
		end
	end

	#######
	# Calculate target calories according to user prefered changerate.
	#######
	def get_target_calories(profile, weight)
		if profile.gender && profile.height && profile.age && profile.activity && weight && profile.changerate
			bmr_maintenance = harrisbenedict(profile.gender, profile.height, profile.age, weight, profile.activity)

			new_target_calories = (bmr_maintenance[:maintenance] + (1000 * profile.changerate)).round(0) # 1kg fat = 7000 kcal, 1 kg a week change = +-1000 a day.

			if new_target_calories != profile.caltarget
				profile.update_attributes(caltarget: new_target_calories)
			end
			return new_target_calories
		else
			return nil
		end
	end

	def bodylog_by_date(created_at)
		date = created_at.to_date

		user = current_user
		bodylog = user.bodylogs.where(created_at: date.beginning_of_day..date.end_of_day)
		return bodylog[0]
	end

	def get_total_reps_sets_weight(workout)
		exercises = workout.exercises.all
		totalReps = 0
		totalSets = 0
		totalWeight = 0
		exercises.each do |e|
			e.segments.each do |s|
				totalSets += 1
				totalReps += s.reps
				totalWeight += (s.weight * s.reps)
			end
		end
		return {totalsets: totalSets, totalreps: totalReps, totalweight: totalWeight}
	end

end

app/views/results_pages/_bodylogstable.html.erb
<br>
<div class="small-12 columns">
	<div class="row">
		<% if @bodylogsTable.empty? %>
			<div class="panel">
				<p> You must first <%= link_to "enter a body stat", new_bodylog_path %> in order to see the
				     the bodylog results table. </p>  
		    </div>
		<% else %>
			<div class="row">
				<div style="align:right;" class="small-4 columns">
					<%= select_month(Date.today) %>
				</div> 
				<div class="small-4 columns">
					<%= select_year(Date.today) %>
				</div>
			</div>
			<table>
				<thread>
					<tr>
						<th width ="150">Date</th>
						<th width ="100">Weight</th>
						<th width ="100">Bodyfat %</th>
						<th width ="100">Calories</th>
						<th width ="100">Deficit/Surplus</th>
						<th width ="100"> </th>				
					</tr>
				</thread>
				<tbody>
					
					<% @bodylogsTable.each do |bodylog| %>
					<tr>
						<td><%= best_in_place bodylog, :created_at, display_with: lambda { |dt| format_date(dt) } %></td>
						<% if bodylog.weight != nil %>
							
							<% if target_weight_reached(bodylog.weight) %>
								<td><span data-tooltip style="color:green;" class="has-tip" title= "You're at your target weight!"><%= best_in_place bodylog, :weight %></span></td>
							<% else %>
								<td><%= best_in_place bodylog, :weight %></td>
							<% end %>
						<% else %>
							<td><%= best_in_place bodylog, :weight %></td>
						<% end %>
						<td><%= best_in_place bodylog, :bodyfat %></td>
						<td><%= best_in_place bodylog, :kcal %></td>
						<% if bodylog.kcal != nil && bodylog.weight != nil && @profile.gender != nil && @profile.height != nil && @profile.activity != nil && @profile.age != nil%>
							<% expenditure =  harrisbenedict(@profile.gender, @profile.height, @profile.age, bodylog.weight, @profile.activity) %>
							<%  difference = bodylog.kcal - expenditure[:maintenance].to_int %>
								
								<% if target_kcal(@profile.caltarget, bodylog.kcal) == nil %>
									<td> <%= difference%> kcal</td>
								<% elsif target_kcal(@profile.caltarget, bodylog.kcal) %>
									<td style='color:green;'> <%= difference %> kcal</td>
									<% else %>
									<td style='color:red;'> <%= difference %> kcal</td>
								<% end %>
						<% else %>
						<td><span data-tooltip class="has-tip" title="To view this please fill in your profile data in your user profile page (click the '-' next to the profile item)"> - </span></td>

						<% end %>
						<td><div class="" style="margin:0;"><%= button_to 'Delete', bodylog, method: :delete, confirm: 'Are you sure?', class:"tiny button alert"%></div></td>
					</tr>
					 <% end %>		
				</tbody>
			</table>

		<% end %>
	</div>
</div>

<%= will_paginate @bodylogsTable, renderer: FoundationPagination::Rails %>

app/views/results_pages/_calendar.html.erb
<div id="calendar">
	<h2 id="month">
		<%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y/%m") %>
		<%= h @date.strftime("%B %Y") %>
		<%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y/%m") %>
	</h2>
	<%= calendar_for @bodylogs, :year => @date.year, :month => @date.month do |calendar| %>
		<%= calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') %>
		    <%= calendar.day(:day_method => :created_at) do |date, bodylogs| %>
		     <%= date.day %>
			     <ul>
				<% for bodylog in bodylogs %>
			      	<li><b>Calories:</b> <%= best_in_place bodylog, :kcal %></li>
			      	<li><b>Weight:</b> <%= best_in_place bodylog, :weight %></li>
			      	<% if bodylog.bodyfat %>
			      		<li><b>bf:</b> <%= best_in_place bodylog, :bodyfat %>%</li>
			      <% end %>
			         </ul>
				<% end %>

				<% workouts = @user.workouts.where("strftime('%m/%d/%Y', created_at) = ?", date.strftime('%m/%d/%Y')) %>
				<% if workouts != nil %>
					<ul>
					<% for workout in workouts %>
						<li><b>Workout:</b> <%= workout.name %></li>
					<% end %>
					</ul>		
				<% end %>
	      	
	<% end %>
	 <% end %>
</div>

app/views/results_pages/_charts.html.erb
<div class="center">
	<div class="panel">
		<br>
		<br>
		
		<div id="bodylogs_chart"></div>
		
		<br>
		<ul class="button-group round">
			<li>
				<button class="tiny button secondary" id="hidekcal_bodylog">Hide kcal</button>
			</li>
			<li>
				<button class="tiny button secondary" id="hideweight_bodylog">Hide weight</button>
			</li>
		</ul>
	</div>

	<br>
	<br>

	<div class="panel">
		
		<div id="workouts_chart"></div>
		
		<br>
		
		<div class="row">
			<div class="large-4 columns">
					<ul class="button-group round">
						<li>
							<button class="tiny button secondary" id="hidekcal_strength">weight</button>
						</li>	
						<li>
							<button class="tiny button secondary" id="hideweight_strength">kcal</button>
						</li>
					</ul>
			</div>
			<div class="large-4 columns">
				<%= form_tag '/results' do %>
					<%= select_tag(:exercise, options_for_select(@exercises.map {|e| [e, e]}), :selected => params[:exercise])%>
			</div>
		
			<div class="large-4 columns">
				<%= submit_tag "Get chart", class: "tiny button alert" %>
				<% end %>
			</div>
			
		</div>
	</div>
</div>

app/views/results_pages/_exercises_table.html.erb
<h3><%= e.name %></h3>

<br>
<% e.segments.each do |s| %>
	<ul>
		<% if check_pr(s, e) %>
			<span data-tooltip class="has-tip" title="PR: 1-rep max: <b><%= number_with_precision(s.strength, precision: 1)%></b>  (only calculated for 10 reps or less)">
				<div style="color:red;">
				 	<li><%= render 'segments_table', s: s %></li>
				</div>
			</span>
		<% else %>
			<li>
				<%= render 'segments_table', s: s %>
			</li>
		<% end %>
	</ul>
<% end %>

app/views/results_pages/_segments_table.html.erb
<%= s.reps %> x <%= s.weight %> <% if s.intensity != nil %> intensity: <%= s.intensity %> <% end %>

app/views/results_pages/_workoutstable.html.erb
<br>
<div class="row">
  <div>
    <% if @workoutsTable.empty? %>
      <div class="panel">
       <p> You must first <%= link_to "enter a workout log", new_workout_path %> in order to see the
            the workout results table.</p>      
      </div>
     
    <% end %>
    <dl class="accordion" data-accordion>
        <% @workoutsTable.each do |workout| %>
      <dd>
        <a href="#<%= workout.id %>"> <%= workout.created_at.strftime("%d %b. %Y") %> | <%= workout.name %></a>
        <div id="<%= workout.id %>" class="content">

        
          <div class="panel">
            <% if workout.comment && !workout.comment.blank? %>
              <h2>Comment</h2>
              <p><%= workout.comment %></p> 
            <% end %>
            <% if workout.rating %>
              <p>Rating: <b><%= display_workout_rating(workout.rating) %></b></p>
            <% end %>
            <% workoutStats = get_total_reps_sets_weight(workout) %>
            <% if workoutStats[:totalsets] %>
              <h2>Stats</h2>

              padding-left: ;<li>Total sets:  <b><%= workoutStats[:totalsets] %></b></li>
              <li>Total reps: <b><%= workoutStats[:totalreps] %></b></li>
              <li>Total weight moved: <b><%= workoutStats[:totalweight] %> kg</b></li>
            <% end %>
          </div>


          <% workout.exercises.each do |e| %>
            <%= render 'exercises_table', e: e %>
          <% end %>

          <% workout.cardios.each do |c| %>
            <%= render 'cardios_table', c: c %>
          <% end %>
          
<ul class="button-group">
  <li>
     <%= link_to "edit", edit_workout_path(workout), class: 'tiny button secondary' %>  </li>
  <li>
    <%= button_to "delete", workout_path(workout.id), confirm: "Are you sure?", method: :delete, class: 'tiny button alert' %>
  </li>
</ul>
           
  
            
        </div>
      </dd>
        <% end %>
    </dl>

    <br>
    <br>
    <div class="row">

    <br>
    <%= will_paginate @workoutsTable, renderer: FoundationPagination::Rails %>
    </div>
  </div>
</div>

app/views/results_pages/index.html.erb
<% provide(:title, 'Results') %>

<h1>Results</h1>
<br>


<div class="large-8 large-centered columns">
	<div class="row">
		<dl class="tabs" data-tab>
		  <dd class="active"><a href="#panel2-1">Charts</a></dd>
		  <dd><a href="#panel2-2">Workouts Table</a></dd>
		  <dd><a href="#panel2-3">Bodystats Table</a></dd>
			<dd><a href="#panel2-4">Calendar</a></dd>
		</dl>
</div>

<div class="large-10 large-centered columns">
</div>
	<div class="tabs-content">
	<div class="content active" id="panel2-1">
		<%= render partial: "charts" %>
		 
	</div>
	<div class="content" id="panel2-2">
		<%= render partial: "workoutstable" %>
	</div>
	<div class="content" id="panel2-3">
		<%= render partial: "bodylogstable" %>
	</div>
	<div class="content" id="panel2-4">
		<%= render partial: "calendar" %>
	</div>
</div>