config/routes.rb
Logbook::Application.routes.draw do 
  resources :contact_forms, only: [:new, :create]
  resources :users do
     resource :profile, :controller => 'profile'
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :bodylogs
  resources :workouts
  resources :settings, :controller => 'settings', only: [:show, :update]
 
 
  root 'static_pages#home'
  match '/results', to: 'results_pages#index', via: 'post'
  match '/results', to: 'results_pages#index', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout',  to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'contact_forms#new', via: 'get'
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		WorkoutBook by Kim Landeweer
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title(yield(:title)) %></title>

	<%= stylesheet_link_tag "application", media: "all" %>

    <%= javascript_include_tag "vendor/modernizr" %>
       
    <%= include_gon %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class="off-canvas-wrap">
      <div class="inner-wrap">
        <nav class="tab-bar">
          <% if signed_in? %>
            <section class="left-small">
              <a class="left-off-canvas-toggle menu-icon" ><span></span></a>
            </section>
           <% end %>
          <section class="middle tab-bar-section">
            <h1 class="title">GYM REGIME</h1>
          </section>

          <section class="right-small">
        <a class="right-off-canvas-toggle menu-icon" ><span></span></a>
          </section>
        </nav>

        <% if signed_in? %>
        <aside class="left-off-canvas-menu">
          <ul class="off-canvas-list">
            <li><label>Logbook</label></li>
            <li><%= link_to "Workout entry", new_workout_path %></li>
            <li><%= link_to "Bodystat entry", new_bodylog_path %></li>
            <li><label></label></li>
            <li><%= link_to "Results", '/results' %></li>
          </ul>
        </aside>
       <% end %>

        <aside class="right-off-canvas-menu">
          <ul class="off-canvas-list">
          <% if signed_in? %>
            <li><label>User</label></li>
            <li><%= link_to "Dashboard", user_profile_path(current_user) %></li>
            <li><%= link_to "Settings", setting_path(current_user) %></li>
            <li><label>Account</label></li>
              <li><%= link_to "Edit Account", edit_user_path(current_user) %></li>
              <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              <li><label></label></li>
              <li><%= link_to "Help", help_path %></li>
              <li><%= link_to "Contact", contact_path %></li>


          <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
          <li><%= link_to "Sign Up", signup_path %></li>
          <% end %>
            </ul>
        </aside>


        <section class="main-section">
          <!-- content goes here -->         
            <%= render 'shared/notice' %>
          <%= yield %>
        </section>

      </div>
    </div>

    <%= render 'layouts/footer' %>

    <%= javascript_include_tag "application" %>
  </body>
</html>